### PR TITLE
fix: file size limit

### LINKED ISSUE #196: fileSize limit on fastify-multipart did not throw error
I don't know if I use it correctly or not but it is just pass through if I passing file with size higher than limit.

```js
/*
 * other code
 */

fastify.post('/upload', async function (req, reply) {
    const data = await req.file({
      limits: {
        fileSize: 1 * 1024 * 1024,  // 1mb limit
      }
    })

    await pump(data.file, fs.createWriteStream(data.filename))

    reply.send()
})
```

It write file to my directory, when I expect it to throw error

* *node version*: 14.15.3
* *fastify version*: 3.9.2
* *fastify multipart version*: 3.3.1
* *os*: WSL

### PR DESCRIPTION
**Pull request by climba03003**
This PR resolve #196 by adding a new option `throwFileSizeLimit`.

The option can be configure in two way:

#### Globally
```JS
fastify.register(fastifyMultipart, { throwFileSizeLimit: false })
```

#### Per Functions
```JS
const file = await req.file({ throwFileSizeLimit: false, limits: { fileSize: 17000 } })
const files = await req.files({ throwFileSizeLimit: false, limits: { fileSize: 17000 } })
const parts = await req.parts({ throwFileSizeLimit: false, limits: { fileSize: 17000 } })
```

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -400,6 +400,12 @@ function fastifyMultipart (fastify, options, done) {
         return
       }
 
+      if (opts.throwFileSizeLimit || options.throwFileSizeLimit) {
```
Comment (mcollina) [inline index.js:403]: I would consider those default to `true`. This seems a bug in the original implementation.

**Review by mcollina — CHANGES_REQUESTED** [review]

File: index.js (hunk 1 above)
Comment (climba03003) [reply index.js:403]: We can release a `semver-minor` with false, then go with a `semver-major` with true in another PR.
So, it would not break someone code and allow them to use this feature.

Comment (zekth) [reply index.js:403]: agree with @climba03003 , this bug was there for a certain amount of time so maybe people would break their code if the upgrade is in `semver-minor`

Comment (zekth) [reply index.js:403]: side node `opts` and `options` are kind of confusing. Might be worth to rename those properly.

Comment (climba03003) [reply index.js:403]: I agree that `opts` and `options` are too confusing when I scanning the code. I will take a time to improve this same as what I have done for fastify-swagger. I will mark it as `TODO`. 

The big `refactor` will comes with `semver-major` and the default behavior change.

Comment (mcollina) [reply index.js:403]: I'm happy to bump the major and have a good default.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by StarpTech** [comment]
With that change we can remove the check here https://github.com/fastify/fastify-multipart/blob/5529808b5a97626c9661ecc8683cc1f8a8411e5c/index.js#L465-L469

**Comment by StarpTech** [comment]
@mcollina I think it's the right moment to remove the old callback-API when we bump to a major.

**Comment by mcollina** [comment]
While it pollutes the code, I think it can stay here for a bit longer - there are plenty of people using it.

**Comment by climba03003** [comment]
> 
> 
> With that change we can remove the check here
> 
> https://github.com/fastify/fastify-multipart/blob/5529808b5a97626c9661ecc8683cc1f8a8411e5c/index.js#L465-L469

Do you have any clue why this two cases will fail when I deleted the code you mention?
https://github.com/fastify/fastify-multipart/blob/master/test/multipart-disk.test.js#L140-L261

**Comment by StarpTech** [comment]
> While it pollutes the code, I think it can stay here for a bit longer - there are plenty of people using it.

Version will still exist in the registry.

**Comment by mcollina** [comment]
> Version will still exist in the registry.

The fact that an API is not maintained anymore will cause significant friction to some of our old user base. Given that it has not cause many issues so far, I think it can stay there as it is.

**Comment by StarpTech** [comment]
> The fact that an API is not maintained anymore will cause significant friction to some of our old user base. Given that it has not cause many issues so far, I think it can stay there as it is.

Reasonable but hard to measure. I'd prefer a "legacy" branch to split those interest groups.

**Comment by mcollina** [comment]
@StarpTech anything blocking here?

**Review by StarpTech — APPROVED** [review]
LGTM

**Review by delvedor — APPROVED** [review]
LGTM
